# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  # Pods for TravelApp
  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  target 'TravelApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
